version: '3.8'

services:
  app:
    build: .
    container_name: rolesia-user-rose
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/rolesia
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENTID: clientId
      SPRING_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENTSECRET: secret
      APP_JWT_SECRET: )1ece*=B,Ux+6`qai)k=9L*6aV|-N:Gu-gBOZESYFtHWEXMXKPqlC5EZuhU8znCG9
      APP_JWT_EXPIRATION_MINUTES: 10
      APP_OAUTH2_REDIRECTURI: http://localhost:3000/oauth2/redirect
      APP_CORS_ALLOWED_ORIGINS: http://localhost:3000
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: rolesia-db
    environment:
      POSTGRES_DB: rolesia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
